// OpenCV CPU baseline features

#if defined(__x86_64__) || defined(__i386__) || defined(_M_X64) || defined(_M_IX86)

#define CV_CPU_COMPILE_SSE 1
#define CV_CPU_BASELINE_COMPILE_SSE 1

#define CV_CPU_COMPILE_SSE2 1
#define CV_CPU_BASELINE_COMPILE_SSE2 1

#define CV_CPU_COMPILE_SSE3 1
#define CV_CPU_BASELINE_COMPILE_SSE3 1

#define CV_CPU_COMPILE_SSSE3 1
#define CV_CPU_BASELINE_COMPILE_SSSE3 1

#define CV_CPU_COMPILE_SSE4_1 1
#define CV_CPU_BASELINE_COMPILE_SSE4_1 1

#define CV_CPU_COMPILE_POPCNT 1
#define CV_CPU_BASELINE_COMPILE_POPCNT 1

#define CV_CPU_COMPILE_SSE4_2 1
#define CV_CPU_BASELINE_COMPILE_SSE4_2 1

#define CV_CPU_COMPILE_FP16 1
#define CV_CPU_BASELINE_COMPILE_FP16 1

#define CV_CPU_COMPILE_FMA3 1
#define CV_CPU_BASELINE_COMPILE_FMA3 1

#define CV_CPU_COMPILE_AVX 1
#define CV_CPU_BASELINE_COMPILE_AVX 1

#define CV_CPU_COMPILE_AVX2 1
#define CV_CPU_BASELINE_COMPILE_AVX2 1

#define CV_CPU_BASELINE_FEATURES 0, CV_CPU_SSE, CV_CPU_SSE2, CV_CPU_SSE3, CV_CPU_SSSE3, CV_CPU_SSE4_1, CV_CPU_POPCNT, CV_CPU_SSE4_2, CV_CPU_FP16, CV_CPU_FMA3, CV_CPU_AVX, CV_CPU_AVX2

// OpenCV supported CPU dispatched features

#define CV_CPU_DISPATCH_COMPILE_AVX_512F 1

#define CV_CPU_DISPATCH_FEATURES 0, CV_CPU_AVX_512F

#elif defined(__aarch64__) || defined(__arm__) || defined(_M_ARM64) || defined(_M_ARM)

#define CV_CPU_COMPILE_NEON 1
#define CV_CPU_BASELINE_COMPILE_NEON 1

#define CV_CPU_BASELINE_FEATURES 0, CV_CPU_NEON

#define CV_CPU_DISPATCH_FEATURES 0

#else
#error Unknown Architecture
#endif
